sources:
  repo_0:
    type: codeup
    name: bible-ai-chat_0GGm
    endpoint: https://codeup.aliyun.com/6976dc554a29923eb3607d8e/bible-ai-chat.git
    branch: main
    triggerEvents:
    - push
    certificate:
      type: serviceConnection
      serviceConnection: wwg85yfr59ht4qnc
defaultWorkspace: repo_0
stages:
  stage_0:
    name: 构建镜像
    jobs:
      job_0:
        name: Node.js 镜像构建
        runsOn:
          group: public/cn-beijing
          labels: linux,amd64
          container: build-steps-public-registry.cn-beijing.cr.aliyuncs.com/build-steps/alinux3:latest
        steps:
          step_0:
            name: 配置 .npmrc 文件
            step: SetupNpmrc
            with:
              npmPrivateRepoConfigPath: /root/.npmrc
          step_1:
            name: 安装 Node 环境
            step: SetupNode
            with:
              versionType: predefined
              npmType: cnpm
              nodeVersion: '24.11'
              installYarn: false
          step_2:
            name: 执行命令
            step: Command
            with:
              variables:
              - key: OSS_ACCESS_KEY_ID
                value: YOUR_OSS_KEY_ID
              - key: OSS_ACCESS_KEY_SECRET
                value: YOUR_OSS_KEY_SECRET
              ifGivenShell: false
              run: |-
                # input your command here
                npm install
                npm run build:web
          step_3:
            name: 镜像构建并推送至ACR（个人版）
            step: DockerBuildPushACR
            with:
              artifact: artifact
              dockerfilePath: Dockerfile
              dockerRegistry: crpi-jla89lkg02vybhoy.cn-hangzhou.personal.cr.aliyuncs.com/frankqian/firstdocker
              useVpcAddress: false
              dockerTag: build
              region: cn-hangzhou
              cacheType: remote
              serviceConnection: wey5ypzmmfqymdjy
        driven: auto
        plugins: []
  stage_1:
    name: 部署
    jobs:
      job_0:
        name: Docker部署
        component: VMDockerDeploy
        driven: auto
        with:
          variables:
          - key: APP_NAME
            value: rtcserver
          - key: ALIYUN_APP_KEY
            value: bb194cf6626d48a888fc4257e4361106
          - key: IMAGE
            value: crpi-jla89lkg02vybhoy.cn-hangzhou.personal.cr.aliyuncs.com/frankqian/firstdocker:build
          - key: DOCKER_PASSWORD
            value: Qianchen_0
          - key: ALIYUN_APP_ID
            value: n5nnqhih
          - key: EXPOSE_PORT
            value: '8200'
          - key: DOCKER_USERNAME
            value: bindoon@sina.com
          - key: DATA_DIR
            value: /data/bible-ai-chat
          useEncode: false
          deployTimeoutPerHost: 240
          pauseStrategy: firstBatchPause
          machineGroup: Z6C1Sa4CsYqFWUmP
          run: |-
            # 1. 登录 (确保域名与 IMAGE 变量中的域名一致)
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin crpi-jla89lkg02vybhoy.cn-hangzhou.personal.cr.aliyuncs.com

            # 2. 拉取最新镜像
            echo "Pulling latest image: ${IMAGE}"
            docker pull "${IMAGE}"

            # 3. 停止并删除旧容器
            if [ "$(docker ps -aq -f name=^${APP_NAME}$)" ]; then
                echo "Stopping and removing existing container: ${APP_NAME}"
                docker stop "${APP_NAME}"
                docker rm "${APP_NAME}"
            fi

            DATA_DIR="/home/admin/rtc/data"

            # 4. 创建数据目录（如果不存在）
            mkdir -p "${DATA_DIR}"

            # 5. 运行新容器
            # 注意：确保 IMAGE 变量包含了完整的私有仓库前缀
            docker run -d --name "${APP_NAME}" \
                -p "${EXPOSE_PORT}:80" \
                -e JAVA_OPTS="-Xms256m -Xmx256m" \
                -v /etc/localtime:/etc/localtime:ro \
                -v "${DATA_DIR}:/app/server/data" \
                --restart unless-stopped \
                "${IMAGE}"

            echo "Container ${APP_NAME} started successfully"

            # 等待应用启动
            echo "Waiting for application to start..."
            timeout 300 bash -c 'until curl -s http://localhost:${EXPOSE_PORT}/health; do sleep 5; done' || (echo "Application failed to start" && exit 1)

            echo 'Deployment completed successfully'
          executeUser: root
          batchNumber: 2
        plugins: []

